<a href="https://colab.research.google.com/github/Evianitary18/Programming-With-Python/blob/main/Simply_EDA_for_Analyst_E_commerce_Revenue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preparation

In [1]:
# import library
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.linear_model import LinearRegression
from scipy.stats import zscore
import statsmodels.api as sa
import statsmodels.formula.api as sm
%matplotlib inline



In [2]:
# code untuk menghilangkan warning message saat menjalankan code di bawah
import warnings
warnings.filterwarnings('ignore')


In [3]:
# Load data kita ke sebuah dataframe bernamaa
df_project = pd.read_excel('Ecommerce_Final.xlsx')
df_project.head()


InvoiceNo StockCode                                       Product_name  \
0     536370      POST  Reffair AX30 [MAX] Portable Air Purifier for C...   
1     536370     22726  Wayona Nylon Braided USB to Lightning Fast Cha...   
2     536370     21724  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...   
3     536370     21913  Sounce Fast Phone Charging Cable & Data Sync U...   
4     536370     21035  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...   

                  Category         InvoiceDate  Quantity  UnitPrice(€)  \
0          Car & Motorbike 2010-12-01 08:45:00        15         18.00   
1  Computers & Accessories 2010-12-01 08:45:00       118          3.75   
2  Computers & Accessories 2010-12-01 08:45:00       106          0.85   
3  Computers & Accessories 2010-12-01 08:45:00        96          3.75   
4  Computers & Accessories 2010-12-01 08:45:00        61          2.95   

   Disc_type  CustomerID        Country Market_id   Region  
0          1       12583  United States        US     East  
1          1       12583      Australia      APAC  Oceania  
2          3       12583      Australia      APAC  Oceania  
3          1       12583        Germany        EU  Central  
4          1       12583        Senegal    Africa   Africa

# EDA

In [4]:
df_project.shape

(35185, 12)

In [5]:
df_project

InvoiceNo StockCode                                       Product_name  \
0         536370      POST  Reffair AX30 [MAX] Portable Air Purifier for C...   
1         536370     22726  Wayona Nylon Braided USB to Lightning Fast Cha...   
2         536370     21724  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...   
3         536370     21913  Sounce Fast Phone Charging Cable & Data Sync U...   
4         536370     21035  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...   
...          ...       ...                                                ...   
35180     569018     21210  boAt Type C A325 Tangle-free, Sturdy Type C Ca...   
35181     569018     23368  Duracell USB Lightning Apple Certified (Mfi) B...   
35182     569018     23508        Flix Micro Usb Cable For Smartphone (Black)   
35183     569018     23076  Ambrane Unbreakable 3 in 1 Fast Charging Braid...   
35184     569018     22531  Duracell USB C To Lightning Apple Certified (M...   

                      Category         InvoiceDate  Quantity  UnitPrice(€)  \
0              Car & Motorbike 2010-12-01 08:45:00        15         18.00   
1      Computers & Accessories 2010-12-01 08:45:00       118          3.75   
2      Computers & Accessories 2010-12-01 08:45:00       106          0.85   
3      Computers & Accessories 2010-12-01 08:45:00        96          3.75   
4      Computers & Accessories 2010-12-01 08:45:00        61          2.95   
...                        ...                 ...       ...           ...   
35180  Computers & Accessories 2011-09-30 09:25:00        99          1.45   
35181  Computers & Accessories 2011-09-30 09:25:00       124          0.65   
35182  Computers & Accessories 2011-09-30 09:25:00        54          0.42   
35183  Computers & Accessories 2011-09-30 09:25:00        13          1.25   
35184  Computers & Accessories 2011-09-30 09:25:00        39          0.42   

       Disc_type  CustomerID        Country Market_id      Region  
0              1       12583  United States        US        East  
1              1       12583      Australia      APAC     Oceania  
2              3       12583      Australia      APAC     Oceania  
3              1       12583        Germany        EU     Central  
4              1       12583        Senegal    Africa      Africa  
...          ...         ...            ...       ...         ...  
35180          1       12676          China      APAC  North Asia  
35181          3       12676      Australia      APAC     Oceania  
35182          1       12676  United States        US        West  
35183          2       12676  United States        US        East  
35184          3       12676  United States        US        East  

[35185 rows x 12 columns]

In [6]:
df_project.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35185 entries, 0 to 35184
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   InvoiceNo     35185 non-null  int64         
 1   StockCode     35185 non-null  object        
 2   Product_name  35185 non-null  object        
 3   Category      35185 non-null  object        
 4   InvoiceDate   35185 non-null  datetime64[ns]
 5   Quantity      35185 non-null  int64         
 6   UnitPrice(€)  35185 non-null  float64       
 7   Disc_type     35185 non-null  int64         
 8   CustomerID    35185 non-null  int64         
 9   Country       35185 non-null  object        
 10  Market_id     35185 non-null  object        
 11  Region        35185 non-null  object        
dtypes: datetime64[ns](1), float64(1), int64(4), object(6)
memory usage: 3.2+ MB


# Cleaning Data

**1. Missing Value**

In [7]:
#melakukan cek missing value
missing_values = df_project.isnull().sum()
if missing_values.sum() == 0:
    print('Tidak ada missing value')
else:
    print('Terdapat missing value', missing_values)


Tidak ada missing value


**2. Duplikat**

In [8]:
df_project.duplicated().sum()

0

**3. Typo**

In [9]:
# InvoiceNo
df_project.InvoiceNo.unique()

array([536370, 536389, 536403, ..., 569122, 569017, 569018])

In [10]:
# Product_name
df_project.Product_name.unique()

array(['Reffair AX30 [MAX] Portable Air Purifier for Car, Home & Office | Smart Ionizer Function | H13 Grade True HEPA Filter [Internationally Tested] Aromabuds Fragrance Option - Black',
       'Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)',
       'Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)',
       ...,
       'Parker Moments Vector Timecheck Gold Trim Roller Ball Pen (Black)',
       'Camlin Elegante Fountain Pen - Black/Blue/Red',
       'Faber-Castell Connector Pen Set - Pack of 25 (Assorted)'],
      dtype=object)

In [11]:
# Categori
df_project.Category.unique()

array(['Car & Motorbike', 'Computers & Accessories', 'Electronics',
       'Health & Personal Care', 'Home & Kitchen', 'Home Improvement',
       'Musical Instruments', 'Office Products', 'Toys & Games'],
      dtype=object)

In [12]:
# InvoiceDate
df_project.InvoiceDate.unique()

<DatetimeArray>
['2010-12-01 08:45:00', '2010-12-01 10:03:00', '2010-12-01 11:27:00',
 '2010-12-01 13:04:00', '2010-12-01 13:24:00', '2010-12-02 18:27:00',
 '2010-12-03 09:51:00', '2010-12-03 10:36:00', '2010-12-03 10:44:00',
 '2010-12-03 12:20:00',
 ...
 '2011-09-29 15:31:00', '2011-09-29 15:58:00', '2011-09-29 16:38:00',
 '2011-09-29 16:52:00', '2011-09-29 17:52:00', '2011-09-30 12:06:00',
 '2011-09-30 12:58:00', '2011-09-30 13:06:00', '2011-09-30 09:22:00',
 '2011-09-30 09:25:00']
Length: 1550, dtype: datetime64[ns]

In [13]:
# Quantity
df_project.Quantity.unique()

array([ 15, 118, 106,  96,  61,  56,  10,  75, 108,  49,  39, 122,  99,
        23,  54,  79, 124,   3,   8, 150, 104,  68,  34,  64, 111, 133,
        42,  65,   1,  88,  83,  36, 149,  26,  12,  86,  89,  50,  98,
        29,   2, 102,  85, 116,  51, 114, 119,  73, 129,  93, 126,  38,
        74,  76, 136,  25, 141, 100,  32,  97, 134,  94, 132,  87,  17,
       125,  59, 115,   5,  19, 112,  24,  91,  18, 148,  92,  58,  95,
        67, 107,  33,  13,  48, 101, 135,  70,   9,  31, 140,  63,  52,
        47,  35,  46, 138,  40,   4,  60, 142, 123,  69, 139, 127, 110,
         7,  71,  30,  16, 131, 146, 130, 137, 105,  11,  82, 144,  78,
        72,  66,  62,  41,  28,   6,  90, 121,  55, 147,  21,  57, 143,
        27,  14,  20, 103,  80, 113, 117,  53,  81,  45,  37, 120,  44,
       128,  43, 109,  84,  22,  77, 145])

In [17]:
# Disc Type
df_project.Disc_type.unique()

array([1, 3, 2])

In [18]:
# Customer ID
df_project.CustomerID.unique()

array([12583, 12431, 12791, 12662, 12433, 12738, 12686, 13520, 12427,
       12557, 12600, 12779, 12682, 12712, 12793, 12725, 12395, 12567,
       15332, 12647, 12472, 12720, 12763, 12808, 12708, 12681, 12347,
       12709, 12386, 12441, 12766, 12481, 12621, 12683, 12755, 12797,
       12494, 12429, 17097, 12471, 12731, 12785, 12753, 12373, 12775,
       12540, 12676, 12428, 12679, 12866, 12352, 12523, 12569, 12415,
       12524, 14646, 12423, 12473, 13492, 12598, 12710, 12534, 12436,
       12739, 12552, 12674, 12491, 12572, 12553, 12664, 12562, 12559,
       12414, 12437, 12350, 12517, 12449, 12627, 12633, 12593, 12644,
       12378, 12670, 12408, 12474, 12483, 12794, 12375, 12594, 12490,
       12654, 12684, 12364, 12762, 12558, 12700, 12587, 12704, 12695,
       12502, 12464, 12727, 12417, 12500, 12817, 12643, 12601, 12455,
       12359, 12750, 12637, 12615, 12544, 12754, 12410, 17508, 12541,
       12547, 12584, 12678, 17443, 12645, 12705, 12689, 17404, 12626,
       12693, 14335,

In [19]:
# Country
df_project.Country.unique()

array(['United States', 'Australia', 'Germany', 'Senegal', 'New Zealand',
       'Afghanistan', 'Saudi Arabia', 'Brazil', 'China', 'France',
       'Italy', 'Tanzania', 'Poland', 'United Kingdom', 'Mexico',
       'El Salvador', 'Taiwan', 'India', 'Dominican Republic',
       'Democratic Republic of the Congo', 'Indonesia', 'Uruguay', 'Iran',
       'Mozambique', 'Bangladesh', 'Spain', 'Ukraine', 'Nicaragua',
       'Morocco', 'Canada', 'Philippines', 'Austria', 'Colombia',
       'Netherlands', 'Malaysia', 'Ecuador', 'Thailand', 'Somalia',
       'Guatemala', 'Belarus', 'Cambodia', 'South Africa', 'Japan',
       'Russia', 'Egypt', 'Azerbaijan', 'Lithuania', 'Argentina',
       'Lesotho', 'Vietnam', 'Cuba', 'Romania', 'Turkey', 'Cameroon',
       'Hungary', 'Singapore', 'Angola', 'Belgium', 'Pakistan', 'Finland',
       'Ghana', 'Zambia', 'Iraq', 'Liberia', 'Georgia', 'Switzerland',
       'Albania', 'Chad', 'Montenegro', 'Namibia', 'Portugal',
       'Madagascar', 'Sweden', 'Myanmar 

In [20]:
# Market_id
df_project.Market_id.unique()

array(['US', 'APAC', 'EU', 'Africa', 'EMEA', 'LATAM', 'Canada'],
      dtype=object)

In [21]:
# Region
df_project.Region.unique()

array(['East', 'Oceania', 'Central', 'Africa', 'West', 'South',
       'Central Asia', 'EMEA', 'North Asia', 'North', 'Caribbean',
       'Southeast Asia', 'Canada'], dtype=object)

# 4. Outlier

In [22]:
# Membuat fungsi cek outlier
def cek_outlier(data, nama_kolom, batas):

    Q1 = np.percentile(data[nama_kolom], 25)
    Q3 = np.percentile(data[nama_kolom], 75)
    IQR = Q3 - Q1

    if batas == 'upper_bound':
        bound = np.where(data[nama_kolom] > (Q3 + 1.5 * IQR))
    elif batas == 'lower_bound':
        bound = np.where(data[nama_kolom] < (Q1 - 1.5 * IQR))
    else:
        raise ValueError("Parameter 'batas' harus 'upper_bound' atau 'lower_bound'.")

    return list(bound[0])

In [23]:
# Menjalankan fungsi untuk mendapatkan indeks yang merupakan outlier pada kolom 'Quantity'
upper_skor_akhir= cek_outlier(df_project, 'Quantity', 'upper_bound')
print("Indeks outlier upper bound untuk kolom 'Quantity':", upper_skor_akhir)

lower_skor_akhir= cek_outlier(df_project, 'Quantity', 'lower_bound')
print("Indeks outlier lower bound untuk kolom 'Quantity':", lower_skor_akhir)

# Menampilkan jumlah total outlier pada kolom 'price'
print(f"Jumlah total outlier pada kolom 'Quantity' sebanyak: {len(upper_skor_akhir) + len(lower_skor_akhir)}")

Indeks outlier upper bound untuk kolom 'Quantity': []
Indeks outlier lower bound untuk kolom 'Quantity': []
Jumlah total outlier pada kolom 'Quantity' sebanyak: 0
